{% set name = "pyremap" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MPAS-Dev/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 746888e14fcc03f92940a51cd0fa9681ae482ec2c04904f687694b5679c6b24f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - netcdf4
    - xarray >=0.10.0
    - dask
    - nco >=4.8.1
    - esmf
    - pyproj

test:
  requires:
    - pytest
  commands:
    - pytest --pyargs pyremap
  imports:
    - pyremap

about:
  home: https://github.com/MPAS-Dev/pyremap
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python remapping tools for climate and earth system models.
  doc_url: https://pyremap.readthedocs.io/en/latest/
  dev_url: https://github.com/MPAS-Dev/pyremap

extra:
  recipe-maintainers:
    - xylar
