{% set name = "pyremap" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MPAS-Dev/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 318a8921bffee5bcf839da131ae39185af96396faa5ff0a460ba2785d51a2203

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [win or py<36]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - netcdf4
    - xarray >=0.10.0
    - dask
    - nco >=4.8.1
    - pyproj

test:
  requires:
    - pytest
  commands:
    - pytest --pyargs pyremap
  imports:
    - pyremap

about:
  home: https://github.com/MPAS-Dev/pyremap
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python remapping tools for climate and earth system models.'
  doc_url: https://pyremap.readthedocs.io/en/latest/
  dev_url: https://github.com/MPAS-Dev/pyremap

extra:
  recipe-maintainers:
    - xylar
